name: ROS2 CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    steps:
    - name: Setup Workspace
      shell: bash
      run: |
        mkdir -p ~/ros_ws/src/
        cd ~/ros_ws
        colcon build
        source install/setup.bash

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: ~/ros_ws/src

    # Checkout generate_parameter_library
    - name: Clone generate_parameter_library
      shell: bash
      run: |
        cd ~/ros_ws/src
        git clone https://github.com/picknikrobotics/generate_parameter_library.git

    - name: Install dependencies
      shell: bash
      run: |
        cd ~/ros_ws
        apt-get update
        apt-get install -y python3-pip
        pip3 install pytest pytest-cov flake8 black isort pre-commit
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    # - name: Run pre-commit checks
    #   shell: bash
    #   run: |
    #     cd ~/ros_ws/src
    #     ls
    #     cd ~/ros_ws/src/ros2-dev-challenge
    #     ls
    #     pre-commit install
    #     pre-commit run --all-files

    - name: Build
      shell: bash
      run: |
        cd ~/ros_ws
        . /opt/ros/humble/setup.bash
        colcon build
        
    - name: Run tests
      shell: bash
      run: |
        cd ~/ros_ws
        . /opt/ros/humble/setup.bash
        . install/setup.bash
        colcon test --packages-select ros2_wave_pkg
        colcon test-result --verbose

    - name: Run linting
      shell: bash
      run: |
        cd ~/ros_ws
        flake8 src/ros2_wave_pkg
        black --check src/ros2_wave_pkg
        isort --check-only src/ros2_wave_pkg